### ISSUE TITLE
Size is determined incorrectly

### ISSUE THREAD

**Issue by unleftie** [cryptpad/cryptpad#1259]
### Description

Hi, when I insert a file from a clipboard, I get a size that is very different from the original:

- MacOS (Docker Desktop), Numbers, resulting file size is ~100 MB **(screenshot 1)**
- Windows (Docker Desktop, Debian + WSL), Microsoft Excel, resulting file size is ~25 MB

![2023-10-01_15-27](https://github.com/cryptpad/cryptpad/assets/23164223/033b9dcb-e692-4df4-aec9-03ee0d8301bb)

The resulting file size is different when importing a local file [directly](https://docs.cryptpad.org/en/FAQ.html#spreadsheets-import-export) rather than via a clipboard. I was getting a ~2 MB file.

My issue probably relates to [1](https://github.com/cryptpad/cryptpad/issues/398) and [2](https://github.com/cryptpad/cryptpad/issues/318).

I am attaching an [example](https://github.com/cryptpad/cryptpad/files/12777228/Archive.zip) of my original file.

### Steps to reproduce

1. Deploy instance locally using Docker Compose (reproduced with `version-5.4.0` and `version-5.4.1`)

```yaml
services:
  cryptpad:
    image: "cryptpad/cryptpad:version-5.4.1"
    hostname: cryptpad

    environment:
      - CPAD_MAIN_DOMAIN=http://cryptpad.localhost
      - CPAD_SANDBOX_DOMAIN=http://cryptpad-sandbox.localhost
      - CPAD_CONF=/cryptpad/config/config.js

    volumes:
      - "blob:/cryptpad/blob"
      - "block:/cryptpad/block"
      - "data:/cryptpad/data"
      - "datastore:/cryptpad/datastore"
      - "customize:/cryptpad/customize"
      - "config:/cryptpad/config"

    ports:
      - "80:3000"
      - "3001:3001"
      - "3003:3003"

    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000

volumes:
  blob:
  block:
  data:
  datastore:
  customize:
  config:
```

2. Sign up + Log in
3. Create a new spreadsheet
4. Insert specified document from a clipboard

I tried deploying 10 times in a row while cleaning up the files, and this behavior is not always reproduced. I can only reproduce the problem locally, but not on your cryptpad.fr instance

### Expected behavior

The size of the imported file via clipboard should be close to the original.

### What opreating system are you using?

Microsoft Windows, Apple macOS

### What browsers are you seeing the problem on?

Mozilla Firefox, Google Chrome

### Extensions

Tried turning everything off

### Version

5.4.1
