### ISSUE TITLE
Production Compose example

### ISSUE THREAD

**Issue by almereyda** [cryptpad/cryptpad#1266]
### Description

Thy `cryptpad/cryptpad` repository has adopted a Docker image, which was before known as `promasu/docker`, now archived in `cryptpad/docker`. According to the documentation, this is officially supported:

* [Docker — Installation — CryptPad 5.4 documentation](https://docs.cryptpad.org/en/admin_guide/installation.html#docker)

While a stable default [`Dockerfile`](https://github.com/cryptpad/cryptpad/blob/main/Dockerfile) is provided, no production example of a [`compose.yml`](https://github.com/cryptpad/cryptpad/blob/main/docker-compose.yml) exists that would integrate the needed reverse proxy. The example configuration clearly states:

https://github.com/cryptpad/cryptpad/blob/929ee518635b30cd608d5646df934c73798746e6/docs/example.nginx.conf#L2-L2

### Steps to reproduce

1. Download and run the official Compose manifest.
2. Find it missing a reverse proxy configuration for proper sandboxing.

### Expected behavior

Open sourcing here and releasing into the public domain what we consider a production grade deployment, based on the presence of Træfik in the `web` network. Do with that what you will.

<details><summary>`diff example.nginx.conf nginx.conf`</summary>
<p>

```diff
8,9c8
<     listen 443 ssl http2;
<     listen [::]:443 ssl http2;
---
>     listen 80;
11,12c10,13
<     # Let's Encrypt webroot
<     include letsencrypt-webroot;
---
>     # Set trusted proxy and header containing real client IP
>     set_real_ip_from  172.19.0.0/8;
>     real_ip_recursive on;
>     real_ip_header    X-Forwarded-For;
23,24c24,25
<     set $main_domain "your-main-domain.com";
<     set $sandbox_domain "your-sandbox-domain.com";
---
>     set $main_domain "drive.example.org";
>     set $sandbox_domain "sandbox.drive.example.org";
26,29c27,34
<     # By default CryptPad forbids remote domains from embedding CryptPad documents in iframes.
<     # The sandbox domain must always be permitted in order for the platform to function.
<     # If you wish to enable remote embedding you may change the value below to "*"
<     # as per the commented value.
---
>     # By default CryptPad allows remote domains to embed CryptPad documents in iframes.
>     # This behaviour can be blocked by changing $allowed_origins from "*" to the
>     # sandbox domain, which must be permitted to load content from the main domain
>     # in order for CryptPad to work as expected.
>     #
>     # An example is given below which can be uncommented if you want to block
>     # remote sites from including content from your server
>     # set $allowed_origins "*";
31d35
<     #set $allowed_origins "*";
40,41c44,45
<     set $api_domain "api.your-main-domain.com";
<     set $files_domain "files.your-main-domain.com";
---
>     set $api_domain "${main_domain}";
>     set $files_domain "${main_domain}";
44c48
<     server_name your-main-domain.com your-sandbox-domain.com;
---
>     server_name drive.example.org sandbox.drive.example.org;
50,51d53
<     ssl_certificate /etc/ssl/lets-encrypt/your-main-domain.com/cert;
<     ssl_certificate_key /etc/ssl/lets-encrypt/your-main-domain.com/key;
55d56
<     ssl_dhparam /etc/nginx/dhparam.pem; # openssl dhparam -out /etc/nginx/dhparam.pem 4096
58,64c59
<     ssl_session_timeout 1d;
<     ssl_session_cache shared:MozSSL:10m;
<     ssl_session_tickets off;
< 
<     ssl_protocols TLSv1.2 TLSv1.3;
<     ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
<     ssl_prefer_server_ciphers off;
---
> 
70,71d64
<     ssl_stapling on;
<     ssl_stapling_verify on;
74d66
<     ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
93c85
<     root /home/cryptpad/cryptpad;
---
>     root /cryptpad;
182,187c174
<         # XXX
<         # static assets like blobs and blocks are served by clustered workers in the API server
<         # Websocket traffic still needs to be handled by the main process, which means it needs
<         # to be hosted on a different port. By default 3003 will be used, though this is configurable
<         # via config.websocketPort
<         proxy_pass http://localhost:3003;
---
>         proxy_pass http://app:3003;
213c200
<         proxy_pass http://localhost:3000;
---
>         proxy_pass http://app:3000;
226,230c213
<     # Requests for blobs and blocks are now proxied to the API server
<     # This simplifies NGINX path configuration in the event they are being hosted in a non-standard location
<     # or with odd unexpected permissions. Serving blobs in this manner also means that it will be possible to
<     # enforce access control for them, though this is not yet implemented.
<     # Access control (via TOTP 2FA) has been added to blocks, so they can be handled with the same directives.
---
>     # encrypted blobs are immutable and are thus cached for a year
242,243d224
<         # Since we are proxying to the API server these headers can get duplicated
<         # so we hide them
248c229
<         proxy_pass http://localhost:3000;
---
>         proxy_pass http://app:3000;

```

</p>
</details> 

<details><summary>`nginx/Dockerfile`</summary>
<p>

```dockerfile
FROM cryptpad/cryptpad:version-5.4.1 AS source
FROM nginx:alpine AS app
COPY --from=source --chown=nginx /cryptpad /cryptpad
```

</p>
</details> 

<details><summary>`compose.yml`</summary>
<p>

```yml
networks:

  web:
    external: true

  back:

services:

  web:
  
    build:
      context: ./nginx/
      
    depends_on:
    - app

    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/cryptpad.conf

    networks:
    - back
    - web

    labels:

      traefik.enable: true

      traefik.http.services.org-example-drive.loadbalancer.server.port: 80

      traefik.http.routers.org-example-drive-web.entrypoints: web
      traefik.http.routers.org-example-drive-web.rule: Host(`drive.example.org`,`sandbox.drive.example.org`)
      traefik.http.routers.org-example-drive-web.middlewares: permanent-redirect

      traefik.http.middlewares.permanent-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.permanent-redirect.redirectscheme.permanent: true

      traefik.http.routers.org-example-drive-web-secure.entrypoints: websecure
      traefik.http.routers.org-example-drive-web-secure.rule: Host(`drive.example.org`,`sandbox.drive.example.org`)
      traefik.http.routers.org-example-drive-web-secure.tls: true
      traefik.http.routers.org-example-drive-web-secure.tls.certresolver: letsencrypt
      traefik.http.routers.org-example-drive-web-secure.service: org-example-drive

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        compress: 'true'

  app:
    image: "cryptpad/cryptpad:version-5.4.1"

    environment:

      CPAD_MAIN_DOMAIN: https://drive.example.org
      CPAD_SANDBOX_DOMAIN: https://sandbox.drive.example.org
      CPAD_CONF: /cryptpad/config/config.js

    volumes:
      - ./data/blob:/cryptpad/blob
      - ./data/block:/cryptpad/block
      - ./customize:/cryptpad/customize
      - ./data/data:/cryptpad/data
      - ./data/files:/cryptpad/datastore
      - ./data/config.js:/cryptpad/config/config.js

    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000

    networks: ["back"]

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        compress: 'true'

```

</p>
</details> 

### Extensions

This field is mandatory, taken from about:support

**Name **|**Typ **|**Version **|**Aktiviert **|**ID**
:-----:|:-----:|:-----:|:-----:|:-----:
British English Dictionary (Marco Pinto)|dictionary|03.02.05|true|marcoagpinto@mail.telepac.pt
Dictionnaire français|dictionary|7.0b|true|fr-dicollecte@dictionaries.addons.mozilla.org
German Dictionary|dictionary|2.1|true|de-DE@dictionaries.addons.mozilla.org
German Dictionary (Switzerland)|dictionary|2.1|true|de-CH@dictionaries.addons.mozilla.org
German Dictionary, extended for Austria|dictionary|2.1|true|de-AT@dictionaries.addons.mozilla.org
ActivityWatch Web Watcher|extension|0.4.8|true|{ef87d84c-2127-493f-b952-5b4e744245bc}
Add-ons Search Detection|extension|2.0.0|true|addons-search-detection@mozilla.com
Amazon.de|extension|1.12|true|amazon@search.mozilla.org
Bing|extension|1.6|true|bing@search.mozilla.org
Bitwarden - Kostenloser Passwortmanager|extension|2023.9.1|true|{446900e4-71c2-419f-a6a7-df9c091e268b}
Browse Later|extension|04.01.00|true|{e39749e2-f9b8-4dcb-ac41-c729c0320888}
Consent-O-Matic|extension|1.0.12|true|gdpr@cavi.au.dk
Container Tabs Sidebar|extension|01.01.00|true|containertabssidebar@maciekmm.net
Copy as Markdown|extension|02.08.03|true|jid1-tfBgelm3d4bLkQ@jetpack
CORS Everywhere|extension|18.11.13.2043|true|cors-everywhere@spenibus
Downloads sidebar|extension|1.0.1|true|{bbb81fb3-49c1-4a42-bcc9-94bc93e19fb8}
DuckDuckGo|extension|1.4|true|ddg@search.mozilla.org
eBay|extension|1.4|true|ebay@search.mozilla.org
Ecosia|extension|1.2|true|ecosia@search.mozilla.org
Enlight|extension|2.7.11.0|true|enlight\_highlightjs@jetpack
Export Tabs URLs|extension|0.2.12|true|{17165bd9-9b71-4323-99a5-3d4ce49f3d75}
Facebook Container|extension|02.03.11|true|@contain-facebook
GNOME Shell-Integration|extension|11.1|true|chrome-gnome-shell@gnome.org
Google|extension|1.4|true|google@search.mozilla.org
Hoppscotch Browser Extension|extension|0.25|true|postwoman-firefox@postwoman.io
I don't care about cookies|extension|03.04.09|true|jid1-KKzOGWgsW3Ao4Q@jetpack
IPFS Companion|extension|03.01.00|true|ipfs-firefox-addon@lidel.org
KeePassXC-Browser|extension|01.08.08|true|keepassxc-browser@keepassxc.org
LEO Eng-Deu|extension|1.1|true|leo\_ende\_de@search.mozilla.org
LessPass|extension|09.06.09|true|contact@lesspass.com
LessPass remoteStorage|extension|0.2.2|true|lesspass@alhur.es
Mastodon – Simplified Federation!|extension|2.1|true|mastodon-auto-remote-follow@rugk.github.io
ModHeader - Modify HTTP headers|extension|04.04.01|true|{ed630365-1261-4ba9-a676-99963d2b4f54}
MyJDownloader Browser Erweiterung|extension|03.03.20|true|jid1-OY8Xu5BsKZQa6A@jetpack
Neat URL|extension|5.0.0|true|neaturl@hugsmile.eu
Passbolt - Open Source Passwort Manager|extension|04.03.01|true|passbolt@passbolt.com
Privacy Badger|extension|2023.9.12|true|jid1-MnnxcxisBPnSXQ@jetpack
Tab Session Manager|extension|06.12.02|true|Tab-Session-Manager@sienori
Tree Style Tab|extension|03.09.17|true|treestyletab@piro.sakura.ne.jp
uBlock Origin|extension|1.52.2|true|uBlock0@raymondhill.net
uMatrix|extension|01.04.04|true|uMatrix@raymondhill.net
Unofficial Hypothesis extension|extension|1.470.0.2|true|{7dc760e7-5cc5-4e76-8468-18b2b003f22a}
Website History Browser|extension|01.03.01|true|{e8f2d1ef-1a55-4aab-9145-fdca2bdc7afb}
Wikipedia (de)|extension|1.3|true|wikipedia@search.mozilla.org
Zotero Connector|extension|5.0.114|true|zotero@chnm.gmu.edu
Language: Deutsch (German)|locale|118.0.20230927.232528|true|langpack-de@firefox.mozilla.org
Language: English (GB)|locale|118.0.20230927.232528|true|langpack-en-GB@firefox.mozilla.org
Language: Français (French)|locale|118.0.20230927.232528|true|langpack-fr@firefox.mozilla.org
Dreamer – Balanced|theme|2.1|true|dreamer-balanced-colorway@mozilla.org
Container Bookmarks|extension|01.02.00|false|{a2d60e98-41cf-4c8a-bd31-ed27352ec0d3}
Adwaita Borderless dark|theme|07.01.02|false|{dd7ce560-8e4b-45b5-91f7-f7af5d23f0da}
Dunkel|theme|1.2|false|firefox-compact-dark@mozilla.org
Firefox Alpenglow|theme|1.4|false|firefox-alpenglow@mozilla.org
Hell|theme|1.2|false|firefox-compact-light@mozilla.org
System-Theme – automatisch|theme|1.3|false|default-theme@mozilla.org

### Version

5.4.1
