### ISSUE TITLE
Missing applications on Docker install

### ISSUE THREAD

**Issue by Magikh42** [cryptpad/cryptpad#1838]
### Description

Hello I installed CryptPad on a Docker container and I selected 4 aplpications but only Sheet and Rich Text appears

### Steps to reproduce

- Install using Docker Compose
- Select applications
- Click on new
- Some selected applications are missing

### Relevant logs

```shell
[Link to logs paste](https://hastebin.ianhon.com/d706)
```

### Expected behavior

It should list all selected applications

### Which operating system are you using?

Linux/BSD/UNIX

### What browsers are you seeing the problem on?

Other

### Extensions

LibreWolf

### Version

2024.12.0

**Comment by ineiti** [comment]
Hi there,

I had a similar problem and remember at least `Sheet` and `Document` missing. In the end it turned out that my nginx configuration was completely wrong. Once I fixed that, I got these applications back.

How do you expose CryptPad to the internet? I use the nginx configuration from here:

https://github.com/cryptpad/cryptpad/blob/main/docs/example.nginx.conf

and then nginx to the docker-compose.yaml using volumes:

```yaml
---
services:
  cryptpad:
    image: "cryptpad/cryptpad:version-2025.3.0"
    hostname: cryptpad
    # [...]

    volumes:
      # [...]

      # Link with nginx
      - dist:/cryptpad/customize.dist
      - www:/cryptpad/www

    networks:
      - cryptpad

    restart: unless-stopped

  nginx:
    image: nginx:latest
    hostname: nginx

    volumes:
      - ./data/cryptpad.conf:/etc/nginx/conf.d/cryptpad.conf
      - dist:/cryptpad/customize.dist
      - www:/cryptpad/www

    networks:
      - cryptpad

    depends_on:
      cryptpad:
        condition: service_started

    labels:
      # traefik labels

    restart: unless-stopped

volumes:
  dist:
  www:

networks:
  cryptpad:
```

Hope that helps.
